# Generated by Django 4.2.1 on 2023-05-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('work', models.CharField(blank=True, max_length=500, null=True)),
                ('data_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=500, null=True)),
                ('oc_key', models.ForeignKey(blank=True, db_column='contact_key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='number', to='contacts.contact')),
            ],
        ),
    ]
